version: "3.9"
services:
  ticket_booking_db:
    container_name: ticket_booking_db
    image: 'ticket_booking_db_image:latest'
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - app_db_net
    environment:
      POSTGRES_DB: ticket-booking-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  ticket_booking_app:
    container_name: ticket_booking_app
    image: 'ticket_booking_app_image:latest'
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    networks:
      - app_db_net
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://ticket_booking_db:5432/ticket-booking-app
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
    depends_on:
      - ticket_booking_db

networks:
  app_db_net:
volumes:
  db_data:
